version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tendermint-db
    restart: always
    environment:
      POSTGRES_DB: tendermint
      POSTGRES_USER: tendermint
      POSTGRES_PASSWORD: tendermint
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

# Тут в будущем добавим отдельный сервис для приложения (Go)
